[package]
name = "rust_stdlinux"
version = "0.1.0"
authors = ["yuziroppe <syani4732@gmail.com>"]
edition = "2018"

[[bin]]
name = "cat"
path = "src/5/cat.rs"
opt-level = 3

[[bin]]
name = "wcl"
path = "src/5/wcl.rs"
opt-level = 3

[[bin]]
name = "head"
path = "src/7/head.rs"
opt-level = 3
